
CREATE TABLE TBL_LOCATIONS (
	LocationId varchar(20) NOT NULL, 
	LocationCode varchar(50) NOT NULL,
	LocationName varchar(100),
	ParentLocation varchar(20) NOT NULL,
	Level tinyint NOT NULL,
	Warehouse varchar(50) NOT NULL,
	path varchar(200), 
	cellRowCode varchar(20)
)
ALTER TABLE TBL_LOCATIONS ADD CONSTRAINT PK_LOCATION PRIMARY KEY (LocationId)
ALTER TABLE TBL_LOCATIONS ADD CONSTRAINT FK_LOCATION_WAREHOUSE FOREIGN KEY (Warehouse) REFERENCES RMD_WAREHOUSE (Name)


CREATE TABLE [dbo].[TBL_ITEM_DEFAULT_LOCATION](
	[Id] [int] NOT NULL,
	[LID] [varchar](20) NOT NULL,
	[MCODE] [varchar](25) NOT NULL
) ON [PRIMARY]
ALTER TABLE [TBL_ITEM_DEFAULT_LOCATION] ADD CONSTRAINT PK_ITEM_DEFAULT_LOCATION PRIMARY KEY (Id)
ALTER TABLE [TBL_ITEM_DEFAULT_LOCATION] ADD CONSTRAINT FK_ITEM_DEFAULT_LOCATION FOREIGN KEY (LID) REFERENCES TBL_LOCATIONS (LocationId) ON DELETE CASCADE
ALTER TABLE [TBL_ITEM_DEFAULT_LOCATION] ADD CONSTRAINT FK_ITEM_DEFAULT_LOCATION_MCODE FOREIGN KEY (MCODE) REFERENCES MENUITEM (MCODE) ON DELETE CASCADE


CREATE TABLE [dbo].[tblStockInVerificationLog](
	[LogId] [int] NOT NULL,
	[DeviceTrnId] [varchar](25) NOT NULL,
	[OrderNo] [varchar](25) NOT NULL,
	[MCODE] [varchar](25) NOT NULL,
	[Quantity] [numeric](18, 12) NOT NULL,
	[RealQty_In] numeric(18,12) NOT NULL,
	[Unit] [varchar](25) NOT NULL,
	[LocationId] [varchar](20) NOT NULL,
	[UserId] [varchar](50) NOT NULL,
	[TrnDate] [datetime] NOT NULL,
	[TrnTime] [varchar](10) NOT NULL,
	[DeviceId] [varchar](200) NULL,
	[SyncDate] [datetime] NOT NULL,
 CONSTRAINT [PK_tblStockInVerificationLog] PRIMARY KEY CLUSTERED 
(
	[LogId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
ALTER TABLE [tblStockInVerificationLog] ADD CONSTRAINT FK_ShipmentInLog_Location FOREIGN KEY (LocationId) REFERENCES TBL_LOCATIONS (LocationId)
ALTER TABLE [tblStockInVerificationLog] ADD CONSTRAINT FK_ShipmentInLog_MCODE FOREIGN KEY (MCODE) REFERENCES MENUITEM (MCODE)
alter table tblStockInVerificationLog Alter Column DeviceId VARCHAR(200)
ALTER TABLE tblStockInVerificationLog ADD CONSTRAINT FK_ShipmentInLog_Devices FOREIGN KEY (DeviceId) REFERENCES tblDevices (DeviceId)
ALTER TABLE tblStockInVerificationLog ADD RealQty_In NUMERIC (18,12) NOT NULL
UPDATE tblStockInVerificationLog set Quantity = 0
ALTER TABLE tblStockInVerificationLog ALTER COLUMN RealQty_In NUMERIC (18,12) NOT NULL

CREATE TABLE RMD_TRNPROD_DETAIL
(
	RecId INT NOT NULL IDENTITY(1,1),
	VCHRNO VARCHAR(15) NOT NULL, 
	DIVISION CHAR(3) NOT NULL,
	PhiscalID VARCHAR(20) NOT NULL,
	MCODE VARCHAR(25) NOT NULL,
	UNIT VARCHAR(10) NOT NULL,
	Warehouse VARCHAR(50) NOT NULL,
	LocationId VARCHAR(20) NOT NULL,
	InQty NUMERIC(8, 2) NOT NULL,
	OutQty NUMERIC (8,2) NOT NULL,
	SNO INT NOT NULL
)

ALTER TABLE RMD_TRNPROD_DETAIL ADD CONSTRAINT PK_TRNPROD_DETAIL PRIMARY KEY (RecId)
ALTER TABLE RMD_TRNPROD_DETAIL ADD CONSTRAINT PK_TRNPROD_DETAIL_TRNMAIN FOREIGN KEY (VCHRNO, DIVISION) REFERENCES RMD_TRNMAIN (VCHRNO, DIVISION) ON DELETE CASCADE
ALTER TABLE RMD_TRNPROD_DETAIL ADD CONSTRAINT PK_TRNPROD_DETAIL_LOCATION FOREIGN KEY (LocationId) REFERENCES TBL_LOCATIONS (LocationId)
ALTER TABLE RMD_TRNPROD_DETAIL ADD CONSTRAINT PK_TRNPROD_DETAIL_MENUITEM FOREIGN KEY (MCODE) REFERENCES MENUITEM (MCODE)
ALTER TABLE RMD_TRNPROD_DETAIL ADD CONSTRAINT PK_TRNPROD_DETAIL_WAREHOUSE FOREIGN KEY (Warehouse) REFERENCES RMD_WAREHOUSE (Name)

CREATE TABLE tblDevices
(
	DeviceId VARCHAR(200) NOT NULL,
	DeviceName VARCHAR(50) NOT NULL	
)
ALTER TABLE tblDevices Add Constraint PK_tblDevices Primary Key (DeviceId)


CREATE TABLE [dbo].[TBL_REQUISITION](
	[ReqId] [int] NULL,
	[Division] [varchar](20) NULL,
	[TDate] [datetime] NULL,
	[TUser] [varchar](50) NULL,
	[Exp_DeliveryDate] [datetime] NULL,
	[IsApproved] [tinyint] NULL
) ON [PRIMARY]

CREATE TABLE [dbo].[TBL_REQUISITION_DETAILS](
	[ReqId] [int] NULL,
	[Mcode] [varchar](20) NULL,
	[Quantity] [int] NULL,
	[ApprovedQty] [int] NULL,
	[Unit] [varchar](20) NULL
) ON [PRIMARY]





